// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuwzQj313CuuX5QtTVdmSIrEVARlIuwxE',
    appId: '1:1000736936073:web:045c15d08e7172aec9b658',
    messagingSenderId: '1000736936073',
    projectId: 'product-db-1b3fd',
    authDomain: 'product-db-1b3fd.firebaseapp.com',
    databaseURL: 'https://product-db-1b3fd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'product-db-1b3fd.appspot.com',
    measurementId: 'G-H4RXH7B97G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8yjbm_OZ08hUgwB40SLwq28WgH_dkKOk',
    appId: '1:1000736936073:android:6b523d6ffef777d8c9b658',
    messagingSenderId: '1000736936073',
    projectId: 'product-db-1b3fd',
    databaseURL: 'https://product-db-1b3fd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'product-db-1b3fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtGjo2Agcpa6eHAlZ7AwmkZ0v2DaaeR-0',
    appId: '1:1000736936073:ios:840060ec99ace24fc9b658',
    messagingSenderId: '1000736936073',
    projectId: 'product-db-1b3fd',
    databaseURL: 'https://product-db-1b3fd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'product-db-1b3fd.appspot.com',
    iosBundleId: 'com.example.product',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtGjo2Agcpa6eHAlZ7AwmkZ0v2DaaeR-0',
    appId: '1:1000736936073:ios:36b18d647041d809c9b658',
    messagingSenderId: '1000736936073',
    projectId: 'product-db-1b3fd',
    databaseURL: 'https://product-db-1b3fd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'product-db-1b3fd.appspot.com',
    iosBundleId: 'com.example.product.RunnerTests',
  );
}
